name = "JuliaMarketFeeder"
uuid = "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
authors = ["Open Finance Julia Contributors"]
version = "0.1.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"

[compat]
julia = "1.9"
DataFrames = "1.6"
HTTP = "1.10"
JSON3 = "1.14"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
